### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by vincekyi** [UCLA-BD2K/metaprot#22]

**Comment by almgong** [comment]
2-5pm: Deployed running elastic beanstalk application, however, we need to set up an access key (pem) to SSH and continue.

**Comment by almgong** [comment]
.ebextension manual commands visible and executed. However there seems to be an issue with intermediate prompts that occur due to some of the commands (like prompts for which mirror to download R libraries). 

Looking into manually installing Rserve from binary source, which should be the last remaining problem.

**Comment by almgong** [comment]
Metaprot successfully deployed at: http://metaprot-env.us-west-2.elasticbeanstalk.com/metabolite-analysis.
