### ISSUE TITLE
High Level Documentation

### ISSUE THREAD

**Issue by vincekyi** [UCLA-BD2K/metaprot#28]

**Comment by almgong** [comment]
@abineetds I have written some of the documentation already at the GitHub wiki page - since my branch right now is volatile (if you merge to your branch you will no longer be able to run the app anymore), can you checkout my branch and attempt to setup the missing pieces using the Wiki I wrote? 

The relevant page is at: https://github.com/UCLA-BD2K/metaprot/wiki/Setup-instructions.

**Comment by almgong** [comment]
2:30-4 Proofread all WikiPages; revised Mongo -> DynamoDB references; added DynamoDB details in appropriate sections
